$fn=360;
generate18650 = false;
generateAA = true;
generateAAA = false;
generateD = false;
generateC = false;
generateCR132A = false;
generate18350 = false;
generateCR2 = false;
generateCR2032 = false;
generate9v = false;
battery_count_x = 5;
battery_count_y = 5;
include <BoxBattery.scad>;
