$fn=360;
generate18650 = true;
generateAA = false;
generateAAA = false;
generateD = false;
generateC = false;
generateCR132A = false;
generate18350 = false;
generateCR2 = false;
generateCR2032 = false;
generate9v = false;
battery_count_x = 1;
battery_count_y = 1;
include <../BoxBattery.scad>;
