name: Rugged Box Auto Build CR2032
on: [push]

jobs:
  Build-STLs:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup - Install tooling
        run: |
          sudo apt-get update
          sudo apt-get install -y openscad
          openscad --version
          admesh --version

      - name: Batch Convert
        run: |
          chmod +x CI.Render.sh
          ./CI.Render.sh CR2032

      - name: Set Artifact Name
        run: echo "ARTIFACT_NAME=CR2032-$(date +'%Y-%m-%d_%H-%M-%S')-${GITHUB_SHA}" | sed 's/[:"]/./g' >> $GITHUB_ENV
  
      - name: Upload Rendered Files
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./render/