name: Rugged Box Auto Build A76
on: [push]

jobs:
  Build-STLs:
    runs-on: openscad/openscad:dev.2024-12-09
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Batch Convert
        run: |
          chmod +x CI.Render.sh
          ./CI.Render.sh A76

      - name: Set Artifact Name
        run: echo "ARTIFACT_NAME=A76-$(date +'%Y-%m-%d_%H-%M-%S')-${GITHUB_SHA}" | sed 's/[:"]/./g' >> $GITHUB_ENV
  
      - name: Upload Rendered Files
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./render/