name: Rugged Box Auto Build Profiles

on: [push]

jobs:
  Build-STLs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup - Install tooling
        run: |
          sudo apt-get update
          sudo apt-get install -y openscad admesh
          openscad --version
          admesh --version

      - name: Batch Convert
        run: |
          chmod +x CI.Render.sh
          ./CI.Render.sh

      - name: Set Artifact Name
        run: echo "ARTIFACT_NAME=profiles-$(date +'%Y-%m-%d_%H-%M-%S')-${GITHUB_SHA}" | sed 's/[:"]/./g' >> $GITHUB_ENV
  
      - name: Upload Rendered Files
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./render/

      # Trigger the coordinator workflow
      - name: Trigger Release Coordinator Workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: aggregate-release
          client-payload: '{"artifact_name": "${{ env.ARTIFACT_NAME }}", "commit_hash": "${{ github.sha }}"}'
