name: Build, Tag, and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository to get access to the Dockerfile
    - name: Checkout repository
      uses: actions/checkout@v3

    # Get the first 9 characters of the commit hash
    - name: Get short Git hash
      id: git-info
      run: echo "GIT_SHORT_HASH=$(git rev-parse --short=9 HEAD)" >> $GITHUB_ENV

    # Log in to Docker Hub (optional, if you want to push the image)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build the Docker image with tags
    - name: Build Docker image
      run: |
        docker build -t robchartier/magic-box:latest .
        docker tag robchartier/magic-box:latest robchartier/magic-box:${{ env.GIT_SHORT_HASH }}

    # Push both tags to Docker Hub
    - name: Push Docker images
      run: |
        docker push robchartier/magic-box:latest
        docker push robchartier/magic-box:${{ env.GIT_SHORT_HASH }}

    # Create a GitHub Release with the Git hash tag
    - name: Create GitHub Release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.GIT_SHORT_HASH }}
        release_name: Docker Image Release ${{ env.GIT_SHORT_HASH }}
        body: |
          Docker image tagged with the Git commit hash.
          - Latest Tag: `robchartier/magic-box:latest`
          - Commit Hash Tag: `robchartier/magic-box:${{ env.GIT_SHORT_HASH }}`
        draft: false
        prerelease: false
