name: Rugged Box Auto Build
on: [push]
jobs:
  Build-STLs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup - Install tooling
        run: |
          sudo apt-get update
          sudo apt-get install -y openscad admesh
          openscad --version
          admesh --version

      - name: Batch Convert
        run: |
          chmod +x CI.Render.sh
          ./CI.Render.sh

      - name: Archive Rendered Files
        run: |
          sudo apt-get install -y p7zip-full
          archive_name=$(date +"%Y-%m-%d_%H-%M-%S").7z
          ls ./render/ -laR
          7z a -t7z -mx=9 $archive_name ./render/

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: rendered-files
          path: "*.7z"
