name: Rugged Box Auto Build D
on: [push]

jobs:
  Build-STLs:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Setup - Install tooling
        run: |
          sudo apt-get update
          sudo apt-get install -y openscad admesh
          openscad --version
          admesh --version

      - name: Batch Convert
        run: |
          chmod +x CI.Render.sh
          ./CI.Render.sh D

      - name: Upload Rendered Files
        uses: actions/upload-artifact@v3
        with:
          name: rendered-files-$(date +"%Y-%m-%d_%H-%M-%S")-${{ github.sha }}
          path: ./render/